### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/jupyterlab-mystjs#6]
### Describe the bug

The CI build step is failing, even though the extension builds locally, deploys and works.
This is perhaps something specific to the ci or test configuration.

### Reproduce the bug

The build badge on the readme is red and git actions fail
https://github.com/executablebooks/jupyterlab-mystjs/actions

**Comment by rowanc1** [comment]
Fixed up the link in #14, the build is broken because tailwind isn't run first. I am not sure how to fix that!

**Comment by agoose77** [comment]
#17 partially fixes this (it runs tailwind). But there's now an error in the `jupyter-releaser` workflow.

I think the CI is now failing because of some assumptions in the jupyter-releaser workflow; `pip install -e .` doesn't populate my CWD with `lib/` assets, so they don't get packaged and found during the jupyter-releaser workflow. I'm not sure what the best solution is here; I don't think you can rely on these artefacts being built without isolation (it might be that pip is building from an sdist in a temp folder) so it points to the action workflow needing to be fixed, not our config

**Comment by agoose77** [comment]
@blink1073 have you seen this anywhere? I don't have the cycles to track it down, so if you already know the answer ... fab! If not, don't worry — I'll get to it in due course. 

We're observing CI failures (see the checks in now-merged #17). It looks like `jupyter-releaser` expects `jlpm run build` to have completed before it builds the TGZ for NPM. However, the CI workflow appears to assume this happens following `pip install -e .` It looks to me like pip might be performing this build in an isolated location and therefore these files are never observed in the source tree. I'm guessing here (this sounds a bit wonky), but it might be a start.

**Comment by blink1073** [comment]
You can do whatever is needed by adding `before-build-python`, like we do in [`jupyter_server`](https://github.com/jupyter-server/jupyter_server/blob/f3fe168bc3a30051d021953e6e3631c794675ef7/pyproject.toml#L282).

**Comment by agoose77** [comment]
@blink1073 dammit, I scoured the configs to find a difference between the cookiecutter and our repo, and _completely_ missed this. I had thought that we were using the default configuration. My mistake! Thanks for dropping by ;)

**Comment by blink1073** [comment]
Happy to help!

**Comment by agoose77** [comment]
Fixed by #23

**Comment by rowanc1** [comment]
Thank you both!! I was working up the courage to tackle this, made my week that you took this on @agoose77!!

**Comment by agoose77** [comment]
No problem. I hate debugging this stuff, so it's nice to ensure it's not tripping anyone else up! I'm mainly benefiting from all the hard work done by the Jupyter team.
